# Pinned submodules provide deterministic, offline configuration after checkout.
set(_solvers_tp "${CMAKE_CURRENT_LIST_DIR}/../ThirdParty")
foreach(_dep eigen magic_enum)
  if(NOT EXISTS "${_solvers_tp}/${_dep}/CMakeLists.txt")
    message(FATAL_ERROR "Missing ThirdParty/${_dep}; run git submodule update --init --recursive")
  endif()
endforeach()
if(NOT TARGET Eigen3::Eigen)
  add_library(Eigen3::Eigen INTERFACE IMPORTED GLOBAL)
  set_target_properties(Eigen3::Eigen PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${_solvers_tp}/eigen")
endif()
if(NOT TARGET magic_enum::magic_enum)
  add_library(solvers_magic_enum INTERFACE)
  target_include_directories(solvers_magic_enum SYSTEM INTERFACE "${_solvers_tp}/magic_enum/include")
  add_library(magic_enum::magic_enum ALIAS solvers_magic_enum)
endif()
# Keep dependency-wide options scoped to this directory, away from the host project.
function(solvers_add_optional_dependencies)
  set(BUILD_TESTING OFF)
  set(BUILD_EXAMPLES OFF)
  set(BUILD_BENCHMARKS OFF)
  if(SOLVERS_ENABLE_CERES AND NOT TARGET Ceres::ceres)
    set(MINIGLOG ON CACHE BOOL "Use Ceres' bundled minimal logger")
    set(GFLAGS OFF CACHE BOOL "Disable gflags")
    set(SUITESPARSE OFF CACHE BOOL "Disable SuiteSparse")
    set(CXSPARSE OFF CACHE BOOL "Disable CXSparse")
    set(LAPACK OFF CACHE BOOL "Disable LAPACK")
    set(WITH_ACCELERATESPARSE OFF CACHE BOOL "Disable Accelerate sparse solvers" FORCE)
    set(Eigen3_DIR "${CMAKE_CURRENT_BINARY_DIR}/eigen-package")
    file(MAKE_DIRECTORY "${Eigen3_DIR}")
    file(WRITE "${Eigen3_DIR}/Eigen3Config.cmake" "set(Eigen3_FOUND TRUE)\nset(EIGEN3_VERSION_STRING 3.4.0)\n")
    include(CMakePackageConfigHelpers)
    write_basic_package_version_file("${Eigen3_DIR}/Eigen3ConfigVersion.cmake" VERSION 3.4.0 COMPATIBILITY SameMajorVersion)
    add_subdirectory("${_solvers_tp}/ceres" "${CMAKE_CURRENT_BINARY_DIR}/ThirdParty/ceres" EXCLUDE_FROM_ALL)
  endif()
  if(SOLVERS_ENABLE_NLOPT AND NOT TARGET nlopt)
    set(NLOPT_TESTS OFF CACHE BOOL "Disable NLopt tests")
    set(NLOPT_PYTHON OFF CACHE BOOL "Disable Python bindings")
    set(NLOPT_OCTAVE OFF CACHE BOOL "Disable Octave bindings")
    set(NLOPT_MATLAB OFF CACHE BOOL "Disable Matlab bindings")
    set(NLOPT_GUILE OFF CACHE BOOL "Disable Guile bindings")
    set(NLOPT_SWIG OFF CACHE BOOL "Disable SWIG bindings")
    add_subdirectory("${_solvers_tp}/nlopt" "${CMAKE_CURRENT_BINARY_DIR}/ThirdParty/nlopt" EXCLUDE_FROM_ALL)
  endif()
endfunction()
solvers_add_optional_dependencies()
if(SOLVERS_ENABLE_TESTING AND NOT TARGET GTest::gtest_main)
  set(INSTALL_GTEST OFF CACHE BOOL "Disable GoogleTest installation")
  set(gtest_force_shared_crt ON CACHE BOOL "Use shared MSVC runtime")
  add_subdirectory("${_solvers_tp}/googletest" "${CMAKE_CURRENT_BINARY_DIR}/ThirdParty/googletest" EXCLUDE_FROM_ALL)
endif()
